version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: "123"
    build:  config-service
    ports:
      - 8081:8081

  discovery-service:
    environment:
      CONFIG_SERVICE_PASSWORD: "123"
    build: discovery-service
    ports:
      - 8082:8082

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: "123"
    build: gateway
    ports:
      - 80:8000

  monitoring-service:
    environment:
      CONFIG_SERVICE_PASSWORD: "123"
    build: monitoring-service
    restart: always
    ports:
      - 8087:8087

