version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672

  mongo-heimdall:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  config:
    build: config-service
    healthcheck:
      test: "exit 0"
    ports:
      - 8081:8081
    expose:
      - 8081

  discovery-service:
    build: discovery-service
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8082:8082

  gateway:
    build: gateway
    ports:
      - 80:8000
    depends_on:
      config:
        condition: service_healthy

  monitoring-service:
    build: monitoring-service
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8085:8085

  heimdall:
    build: heimdall
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8086:8086
