version: '3'


services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"

  mongo-heimdall:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: heimdall
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-heimdall/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  config-service:
    build: config-service
    healthcheck:
      test: "exit 0"
    ports:
      - "8081:8081"

  discovery-service:
    build: discovery-service
    depends_on:
      - config-service
    links:
      - config-service
    ports:
      - "8082:8082"

  gateway:
    build: gateway
    depends_on:
      - config-service
    links:
      - config-service
    ports:
      - "80:8000"

  monitoring-service:
    build: monitoring-service
    depends_on:
      - config-service
    links:
      - config-service
    ports:
      - "8085:8085"

  heimdall:
    build: heimdall
    depends_on:
      - config-service
    links:
      - config-service
    ports:
      - "8086:8086"

